# Default colorshell's kitty configuration, 
# please use the user.conf available in this
# same directory.

include $XDG_CACHE_HOME/wal/colors-kitty.conf
include ./user.conf

# Dinamically update colorscheme with pywal16
allow_remote_control yes
listen_on unix:@kitty

# Style
font_family 0xProto Nerd Font
font_size 10.8
font_weight 340
cursor_trail 6
window_padding_width 5

# Rendering
text_gamma_adjustment 1.7
text_contrast 30

# General
confirm_os_window_close 0
