splash = true

preload = ~/Imagens/Wallpapers/nijika-ijichi-bocchi-the-rock.jpg
wallpaper = , ~/Imagens/Wallpapers/nijika-ijichi-bocchi-the-rock.jpg # use ´contain:´ before wallpaper to preserve original size
