
###############
## AUTOSTART ##
###############
# Wiki: https://wiki.hyprland.org/Configuring/Keywords/#executing


exec-once = uwsm-app colorshell # i use uwsm

exec-once = systemctl start --user --now hyprpolkitagent # Hyprland's PolKit
exec-once = systemctl start --user --now hypridle
exec-once = systemctl start --user --now gnome-keyring-daemon

exec-once = nautilus --gapplication-service # for faster nautilus initialization
exec-once = tuba --gapplication-service # the best mastodon client :3
