
###############
## AUTOSTART ##
###############
# Wiki: https://wiki.hyprland.org/Configuring/Keywords/#executing


exec-once = uwsm-app colorshell

# Security & stuff
exec-once = systemctl start --user hyprpolkitagent
exec-once = systemctl start --user gnome-keyring-daemon

exec-once = colorshell run "tuba --gapplication-service" # the best mastodon client :3
