##############
## BINDINGS ##
##############
# Wiki: https://wiki.hyprland.org/Configuring/Binds


# Uncomment if you want to press SUPER to launch application search
# bind = SUPER, SUPER_L, exec, astal toggle apps-window

bind = SUPER, F11, fullscreen

bind = SUPER, K, exec, colorshell run %terminal
bind = SUPER, Q, killactive
bind = SUPER, E, exec, colorshell run %file_manager
bind = SUPER, F, togglefloating
bind = SUPER, P, pseudo, 
bind = SUPER, J, togglesplit

bind = SUPER, S, togglespecialworkspace, sound
bind = SUPER SHIFT, S, movetoworkspace, special:sound

bind = SUPER, D, togglespecialworkspace, chat
bind = SUPER SHIFT, D, movetoworkspace, special:chat

bind = SUPER, H, togglespecialworkspace, hide
bind = SUPER SHIFT, H, movetoworkspace, special:hide

# Move focus with mainMod + arrow keys
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

# Move windows with keyboard keys
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d 
bind = SUPER SHIFT, C, centerwindow

# Resize windows with arrow keys / hjkl
binde = SUPER ALT, left, resizeactive, -60 0
binde = SUPER ALT, down, resizeactive, 0 60
binde = SUPER ALT, up, resizeactive, 0 -60
binde = SUPER ALT, right, resizeactive, 60 0

binde = SUPER ALT, H, resizeactive, -60 0
binde = SUPER ALT, J, resizeactive, 0 60
binde = SUPER ALT, K, resizeactive, 0 -60
binde = SUPER ALT, L, resizeactive, 60 0

bind = CTRL SUPER, right, workspace, e+1
bind = CTRL SUPER, left, workspace, e-1


# Switch workspaces with SUPER + [0-9]
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# Move active window to a workspace with SUPER + SHIFT + [0-9]
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Move/resize windows with SUPER + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

