# colorshell configuration, please don't modify unless you know what you're doing!


# Animations
windowrule = match:class hyprpolkitagent, animation gnomed
windowrule = match:class xdg-desktop-portal.*, animation gnomed
layerrule = match:namespace selection, animation fade
layerrule = match:namespace hyprpicker, animation fade
layerrule = match:namespace hyprpaper, animation fade
layerrule = match:namespace apps-window, animation slide bottom
layerrule = match:namespace control-center, animation fade
layerrule = match:namespace center-window, animation fade
layerrule = match:namespace logout-menu, animation fade
layerrule = match:namespace runner, animation fade
layerrule = match:namespace background-window, animation fade
layerrule = match:namespace background-window-blur, animation fade
layerrule = match:namespace .*-popup, animation fade
layerrule = match:namespace floating-notifications, no_anim on

# Blur
windowrule {
    name = fix-chromium-xwayland-popup-blur
    match:class = ^()$
    match:title = ^()$

    no_blur = on
}
windowrule = match:class ^(org.kde.kdeconnect..*)$, no_blur on

layerrule {
    name = clsh-top-bar-widget
    match:namespace = top-bar

    blur = on
    ignore_alpha = 0.55
}
layerrule {
    name = clsh-popup-widgets-1
    match:namespace = control-center|center-window|runner|floating-notifications

    blur = on
    ignore_alpha = 0.7
}
layerrule {
    name = clsh-popup-widgets-2
    match:namespace = .*-popup

    blur = on
    ignore_alpha = 0.6
}

layerrule = match:namespace osd, blur on
layerrule = match:namespace apps-window, blur on
layerrule = match:namespace logout-menu, blur on

layerrule = match:namespace osd, ignore_alpha 0.4
layerrule = match:namespace apps-window, ignore_alpha 0.5
layerrule = match:namespace logout-menu, ignore_alpha 0
