general {
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
    inhibit_sleep = 2
}

# lock
listener {
    timeout = 800
    on-timeout = colorshell lock
}

# dpms power save (has problems on amdgpu)
listener {
    timeout = 1800
    #on-timeout = hyprctl dispatch 'hl.dsp.dpms({action="disable"})'
    #on-resume = hyprctl dispatch 'hl.dsp.dpms({action="enable"})'
}

# suspend
listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
