
##############
## MONITORS ##
##############

# Configure yout monitor(s) here! See https://wiki.hyprland.org/Configuring/Monitors for more information on how to do that!

monitor = , preferred, auto, auto, vrr, 1 # vrr enables variable refresh rate for gaming
