
#####################
## NVIDIA SETTINGS ##
#####################

env = LIBVA_DRIVER_NAME, nvidia
env = XDG_SESSION_TYPE, wayland
env = GBM_BACKEND, nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME, nvidia
env = _VK_LAYER_NV_optimus, NVIDIA_only
env = __NV_PRIME_RENDER_OFFLOAD, 1

cursor {
    no_hardware_cursors = true
}

render {
    explicit_sync = true
}
