####################
# HYPRLAND PLUGINS #
####################


plugin {

    # Example plugin configuration
    hyprbars {
        bar_height = 24

        hyprbars-button = rgb(ff4040), 16, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(eeee11), 16, , hyprctl dispatch fullscreen 1
    }
}
