
###############
## AUTOSTART ##
###############

exec-once = /usr/lib/polkit-kde-authentication-agent-1 # exec kde auth agent if app asks for sudo
exec-once = waybar
exec-once = swaync # Run notification center / daemon
exec-once = hyprpaper
exec-once = hypridle # Idle daemon for Hyprland

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store # Stores text
exec-once = wl-paste --type image --watch cliphist store # Stores images


# Apps 
exec-once = /opt/discord/Discord --start-minimized

# Special
exec-once = /home/joaov/.local/share/scripts/fix-nautilus.sh
exec-once = /bin/systemctl enable --now bluetooth
