
###############
## AUTOSTART ##
###############

exec-once = /usr/lib/polkit-kde-authentication-agent-1 # exec kde auth agent if app asks for extra permissions
exec-once = /bin/waybar
exec-once = /bin/swaync # Run notification center / daemon
exec-once = /bin/hyprpaper

# App example 
# exec-once = /opt/discord/Discord --start-minimized

