
#################
## ENVIRONMENT ##
#################

env = XCURSOR_SIZE, 24
env = HYPRCURSOR_SIZE, 24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = ADW_DISABLE_PORTAL,1 # Allows dark theme in adwaita applications
