
##################
## WINDOW RULES ##
##################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ and https://wiki.hyprland.org/Configuring/Workspace-Rules/ for information on how to configure this

# Floating windows
windowrulev2 = float, class:moe.launcher.*
windowrulev2 = float, title:^(Clapper)$
windowrulev2 = float, class:xdg-desktop-portal*
windowrulev2 = float, class:org.pulseaudio.pavucontrol

# Resize
windowrulev2 = size 70% 65%, class:org.pulseaudio.pavucontrol

# Center
windowrulev2 = center, class:org.pulseaudio.pavucontrol

# Animations
windowrulev2 = animation slide right, class:org.pulseaudio.pavucontrol
layerrule = animation slide right, swaync-control-center
layerrule = animation fade, selection
layerrule = animation fade, logout_dialog
layerrule = animation fade, waybar
layerrule = animation fade, hyprpaper
layerrule = animation slide right, swaync-notification-window
layerrule = animation fade, hyprpicker

# Opacity
windowrulev2 = opacity , class:kitty

# Blur
blurls = logout_dialog
blurls = kitty
blurls = waybar

windowrulev2 = suppressevent maximize, class:.*
