
##################
## WINDOW RULES ##
##################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ and https://wiki.hyprland.org/Configuring/Workspace-Rules/ for information on how to configure this

# Floating windows
windowrulev2 = float, class:moe.launcher.*
windowrulev2 = float, title:^(Clapper)$
windowrulev2 = float, title:^(Resources)$
windowrulev2 = float, class:^xdg-desktop-portal*

windowrulev2 = suppressevent maximize, class:.*
