
##################
## WINDOW RULES ##
##################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ and https://wiki.hyprland.org/Configuring/Workspace-Rules/ for information on how to configure this

windowrulev2 = suppressevent maximize, class:.*
